# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://michaelzhou111.github.io
date_format: "ordinal"
title: Michael Zhou's Blog
subtitle: "一个测试行业从业人员的点滴感悟"
description: "Michael Zhou's personal blog"
keywords: 测试开发,自动化测试,工程效率
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: Michael Zhou
organization:
organization_url:
github_username: MichaelZhou111
location: Beijing, China
email: zhouzhiping.michael@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

#   -
#     href: /archives/
#     label: 归档

  -
    href: /wiki/
    label: 技能字典

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 10
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: mzlogin/mzlogin.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: michaelzhou111
# https://imsun.net/posts/gitment-introduction/
# i do not use gitment for now
gitment:
    owner: mzlogin
    repo: blog-comments
    oauth:
        client_id: d2e1cbbd298958076462
        client_secret: b42a4178e5fd4a7cf63189ef4b1453b05c375709
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: MichaelZhou111
    repo: michaelzhou111.github.io
    clientID: 16cde2922493f9824e7b
    clientSecret: e6d14bdd515afc130bcfb3f801b4d512bdbecc78
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-119022278-1

leancloud:
  enable: true
  app_id: 7f1h6TTDyH8x6gvCG5XV32bi-gzGzoHsz
  app_key: 9gVoQ5eKkXCrWiRpEC9TI4Q1
